[build]
# Define the builder type
builder = "DOCKERFILE"

# Specify the path to the Dockerfile
dockerfilePath = "./Dockerfile"

# Define the watch patterns
watchPatterns = [
    "requirements.txt",
    "src/**",
    "railway.toml",
    "Dockerfile"
]